# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Using static frameworks for Firebase
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'telmi' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  # Remove modular_headers since we're using static frameworks
  # pod 'Firebase', :modular_headers => true
  # pod 'FirebaseAuth', :modular_headers => true

    # Add SDWebImage pods
    pod 'SDWebImage'
    pod 'SDWebImageWebPCoder'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
