require_relative '../node_modules/react-native/scripts/react_native_pods'


platform :ios, min_ios_version_supported
prepare_react_native_project!

# Using static frameworks for Firebase
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'telmi' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  # Add SDWebImage pods
  pod 'SDWebImage'
  pod 'SDWebImageWebPCoder'
  
  # Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  
  # VideoSDK
  pod 'react-native-webrtc', :path => '../node_modules/@videosdk.live/react-native-webrtc'

    # Add SDWebImage pods
    pod 'SDWebImage'
    pod 'SDWebImageWebPCoder'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # This is necessary for Xcode 14+
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
